# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor Ruby/Jekyll dependencies in Gemfile
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    # Group related updates together
    groups:
      jekyll:
        patterns:
          - "jekyll*"
        exclude-patterns:
          - "jekyll-theme-*"
    # Auto-merge security patches and patch-level updates
    open-pull-requests-limit: 5
    reviewers:
      - "ulfarsson"  # Update this to the main maintainer's GitHub username
    assignees:
      - "ulfarsson"  # Update this to the main maintainer's GitHub username
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Monitor GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    # Group GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    reviewers:
      - "ulfarsson"  # Update this to the main maintainer's GitHub username
    commit-message:
      prefix: "ci"
      include: "scope"